@baseUrl = http://localhost:8080

### ── Auth ──────────────────────────────────────────────────────

### Register a new user
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "Password123!",
  "captchaToken": "captcha-token"
}

### Login
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@delivery-system.com",
  "password": "Admin@Str0ng!Pass",
  "captchaToken": "captcha-token"
}

### Login with Google
# @name googleLogin
POST {{baseUrl}}/api/auth/google-login
Content-Type: application/json

{
  "token": "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.invalid-signature",
}

### ── Authenticated request  ─────────────────────────────────────

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlODY1ZTU1NS1kZTIyLTRmNjYtZjc5OC0wOGRlODkzMzNkZDEiLCJlbWFpbCI6ImFkbWluQGRlbGl2ZXJ5LXN5c3RlbS5jb20iLCJqdGkiOiIzMzM4MTEzMC1hMjRhLTQ0YTMtYTYzOS03YmNlNDJiOTEwODMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTc3NDMxMjA3MywiaXNzIjoiRGVsaXZlcnlTeXN0ZW0iLCJhdWQiOiJEZWxpdmVyeVN5c3RlbSJ9.N-S0wEXsnN0NrZniGXVArBDt4QsUyP07DGWTojizwnc

### Protected endpoint
GET {{baseUrl}}/api/products
Authorization: Bearer {{token}}
