namespace DeliverySystem.Application.DTOs;

/// <summary>
/// Request payload for completing a password reset.
/// </summary>
/// <param name="UserId">The ID of the user whose password is being reset.</param>
/// <param name="Token">The password reset token generated by Identity and included in the reset link.</param>
/// <param name="NewPassword">The new plaintext password (must meet complexity requirements).</param>
/// <param name="CaptchaToken">The reCAPTCHA token obtained from the client.</param>
public sealed record ResetPasswordRequest(string UserId, string Token, string NewPassword, string CaptchaToken);
